### ISSUE TITLE
Add Cutter/radare2 plugins

### ISSUE THREAD

**Issue by XVilka** [GrammaTech/gtirb-ghidra-plugin#1]
I noticed you have a plugin for Ghidra, but it is not the only one FOSS tool available.
[Radare2](https://github.com/radareorg/radare2) is a highly-portable cross-platform reverse engineering framework and a toolkit without dependencies.  It has support for analyzing binaries, disassembling code, debugging programs, attaching to remote GDB/LLDB, WinDbg servers, rich plugin system (see `r2pm`), and integration with various decompilers. For example, ghidra decompiler plugin - [r2ghidra-dec](https://github.com/radareorg/r2ghidra-dec). It is actively developed and can be easily integrated in various open source and commercial products. I believe, it will be highly beneficial to support these and provide a package for install from `r2pm`, see the package repository here: https://github.com/radareorg/radare2-pm

![image](https://user-images.githubusercontent.com/203261/68269641-7ae24e00-0095-11ea-95f2-cebbc7246954.png)

For documentation on writing plugins for radare2 see [Scripting](https://radare.gitbooks.io/radare2book/content/scripting/intro.html) and [Plugins](https://radare.gitbooks.io/radare2book/content/plugins/intro.html) Radare2 Book chapters.

[Cutter](https://cutter.re/) is a crossplatform Qt/C++ GUI frontend to radare2:

![image](https://user-images.githubusercontent.com/203261/68269343-78332900-0094-11ea-8646-f6226cb6043f.png)

For documentation on writing plugins for Cutter see [the official tutorial](https://cutter.re/docs/plugins.html) and the [curated list](https://github.com/radareorg/cutter-plugins) of various popular plugins.

**Comment by eschulte** [comment]
Thanks for this note.  We have discussed working on a Radare2 plugin, and it is useful to know that there is some demand for this.  In the short term we have additional functionality that we would like to incorporate into our Ghidra plugin.  However, once that is complete--assuming we have the resources--we are interested in the integration of GTIRB with Radare2.  At the same time, if there is anyone with Radare2 experience who would be interested in using the [GTIRB APIs](https://grammatech.github.io/gtirb/usergroup2.html) to build such a plugin we would be very eager to provide any support we can.

I'm going to close this issue as it isn't relevant to our Ghidra plugin, but feel free to create a [GTIRB issue](https://github.com/grammatech/gtirb/issues) to track this request.

**Comment by XVilka** [comment]
@eschulte you can just transfer the issue between repositories in the organization. Probably will be better than to have a copy.
