### ISSUE TITLE
Support GTIRB v2?

### ISSUE THREAD

**Issue by jeshan** [GrammaTech/gtirb-ghidra-plugin#2]
Hello,
Nowadays, running the plugin with `ddisasm` outputs shows an error due to the mismatch:

https://github.com/GrammaTech/gtirb-ghidra-plugin/blob/41ea0b24ad8be808713a8f5ae4d522d8c6d6153f/Gtirb/src/main/java/com/grammatech/gtirb_ghidra_plugin/GtirbLoader.java#L1183-L1188

I have worked around it by just ignoring it!
First, is that a good idea?

Otherwise, I'm thinking that if gtirb v2 is backwards compatible with v1, then it'd be safe to remove this version check, correct?

Looking at the difference when the major version changed at
https://github.com/GrammaTech/gtirb/compare/v1.10.0...v1.10.1

I'm seeing that the only notable difference is the new byte endianness field.

**Comment by tneale-gt** [comment]
They are mostly but not entirely backward compatible, so this is a reasonable short-term workaround. We are working on an update that will be compatible with the latest version of ddisasm, that should be available soon.

**Comment by tneale-gt** [comment]
Latest update fixes this.

**Comment by jeshan** [comment]
I see that only the binary has been committed and not the source changes. Was that intended?

**Comment by tneale-gt** [comment]
Yes, the fix to this problem was to build the plugin with the new GTIRB version, so no source code changes were needed in the plugin.
